{{- if .Values.ingress.create -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  rules:
  {{- if eq .Values.ingress.type "alb" }}
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "explorer.fullname" . }}
              servicePort: 80
  {{- else if eq .Values.ingress.type "nginx" }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: explorer-tls
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: explorer
                port:
                  number: 80
  {{- end }}
{{- end }}
